import "@/styles/globals.css";
import SideMenu from "./(main)/components/SideMenu";
import Content from "./(main)/components/HomePage";
import SideUpdate from "./(main)/components/SideUpdate";

export const metadata = {
  title: "Queue",
  description: "Generated by Next.js",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-slate-200">
        <section className="container mx-auto h-dvh">
          <div className="sticky top-0 z-50 flex h-16 w-[inherit] bg-white p-4 [box-sizing:inherit]">
            fixed heading
          </div>

          <div className="mt-[20px] flex gap-4">
            <SideMenu />
            <div className="relative ml-[270px]">
              <div className="min-w-[500px] max-w-[500px]">{children}</div>
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
